apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visitor-counter-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #   - visitor-counter.example.com
  #   secretName: visitor-counter-tls
  rules:
  - host: visitor-counter.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: visitor-counter-service
            port:
              number: 80