apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visitor-counter-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - APP_HOSTNAME
    secretName: visitor-counter-tls
  rules:
  - host: APP_HOSTNAME
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: visitor-counter-service
            port:
              number: 80
