apiVersion: v1
kind: Secret
metadata:
  name: visitor-counter-secret
type: Opaque
stringData:
  DB_HOST: visitor-counter-postgres-ne.postgres.database.azure.com
  DB_USER: postgresadmin
  DB_PASSWORD: "" # Will be injected at deploy time
  ConnectionStrings__DefaultConnection: "" # Will be injected at deploy time
